### ISSUE TITLE
mysql jdbc plugin not working

### ISSUE THREAD

**Issue by AshishThakur** [elastic/logstash-docker#51]
Hi,

I get following error in logstash docker version 5.5.2
```
logstash_1       | [2017-09-09T17:12:20,535][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>RuntimeError, :message=>"Could not fe
tch the configuration, message: The following config files contains non-ascii characters but are not UTF-8 encoded [\"/usr/share/logstash/pipeline/mysql-connector-java-5.1.44-bin.ja
r\"]", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/agent.rb:155:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90:in `exe
cute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:359:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in
`block in initialize'"]}
```
In case I run logstash natively with docker this error does not appear, is there some missing package in docker image?

**Comment by AshishThakur** [comment]
my bad..found the error. I had added the jar file in pipelines dir which was causing the issue.
