### ISSUE TITLE
Logstash cannot create file log - Permission deneid

### ISSUE THREAD

**Issue by emarcelino** [elastic/logstash-docker#54]
I created a log4j.properties file with the functionality to save my log to a file, in a certain folder.

But when I upload my container I get the following message: Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties

I changed property `path.logs` to `/usr/share/logstash/logs` in file `logstash.yml`.

I already entered the container, gave all possible permissions but it continues to give error.

See the complete exception below:

container         | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
container         | 2017-10-05 20:39:11,989 main ERROR Unable to create file my-logstash.log java.io.IOException: Permission denied
container         | 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
container         | 	at java.io.File.createNewFile(File.java:1012)
container         | 	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:421)
container         | 	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:403)
container         | 	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:73)
container         | 	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:81)
container         | 	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:103)
container         | 	at org.apache.logging.log4j.core.appender.RollingFileAppender.createAppender(RollingFileAppender.java:191)
container         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
container         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
container         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
container         | 	at java.lang.reflect.Method.invoke(Method.java:498)
container         | 	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:132)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:918)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:858)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:850)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:479)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:219)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:231)
container         | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:496)
container         | 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:566)
container         | 	at org.apache.logging.log4j.core.LoggerContext.setConfigLocation(LoggerContext.java:555)
container         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
container         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
container         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
container         | 	at java.lang.reflect.Method.invoke(Method.java:498)
container         | 	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:451)
container         | 	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:312)
container         | 	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
container         | 	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.ast.IfNode.interpret(IfNode.java:116)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
container         | 	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
container         | 	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
container         | 	at org.jruby.runtime.Block.yield(Block.java:142)
container         | 	at org.jruby.ext.thread.Mutex.synchronize(Mutex.java:149)
container         | 	at org.jruby.ext.thread.Mutex$INVOKER$i$0$0$synchronize.call(Mutex$INVOKER$i$0$0$synchronize.gen)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
container         | 	at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
container         | 	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
container         | 	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
container         | 	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.ast.IfNode.interpret(IfNode.java:118)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
container         | 	at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
container         | 	at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
container         | 	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:139)
container         | 	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:187)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)
container         | 	at org.jruby.ast.VCallNode.interpret(VCallNode.java:88)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
container         | 	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:204)
container         | 	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:211)
container         | 	at org.jruby.runtime.callsite.SuperCallSite.cacheAndCall(SuperCallSite.java:366)
container         | 	at org.jruby.runtime.callsite.SuperCallSite.callBlock(SuperCallSite.java:192)
container         | 	at org.jruby.runtime.callsite.SuperCallSite.call(SuperCallSite.java:197)
container         | 	at org.jruby.runtime.callsite.SuperCallSite.callVarargs(SuperCallSite.java:108)
container         | 	at org.jruby.ast.SuperNode.interpret(SuperNode.java:115)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
container         | 	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
container         | 	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
container         | 	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
container         | 	at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
container         | 	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
container         | 	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
container         | 	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
container         | 	at usr.share.logstash.lib.bootstrap.environment.__file__(/usr/share/logstash/lib/bootstrap/environment.rb:71)
container         | 	at usr.share.logstash.lib.bootstrap.environment.load(/usr/share/logstash/lib/bootstrap/environment.rb)
container         | 	at org.jruby.Ruby.runScript(Ruby.java:857)
container         | 	at org.jruby.Ruby.runScript(Ruby.java:850)
container         | 	at org.jruby.Ruby.runNormally(Ruby.java:729)
container         | 	at org.jruby.Ruby.runFromMain(Ruby.java:578)
container         | 	at org.jruby.Main.doRunFromMain(Main.java:393)
container         | 	at org.jruby.Main.internalRun(Main.java:288)
container         | 	at org.jruby.Main.run(Main.java:217)
container         | 	at org.jruby.Main.main(Main.java:197)
container         |
container         | 2017-10-05 20:39:12,055 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile. java.lang.reflect.InvocationTargetException
container         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
container         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
container         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
container         | 	at java.lang.reflect.Method.invoke(Method.java:498)
container         | 	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:132)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:918)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:858)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:850)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:479)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:219)
container         | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:231)
container         | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:496)
container         | 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:566)
container         | 	at org.apache.logging.log4j.core.LoggerContext.setConfigLocation(LoggerContext.java:555)
container         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
container         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
container         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
container         | 	at java.lang.reflect.Method.invoke(Method.java:498)
container         | 	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:451)
container         | 	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:312)
container         | 	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
container         | 	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.ast.IfNode.interpret(IfNode.java:116)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
container         | 	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
container         | 	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
container         | 	at org.jruby.runtime.Block.yield(Block.java:142)
container         | 	at org.jruby.ext.thread.Mutex.synchronize(Mutex.java:149)
container         | 	at org.jruby.ext.thread.Mutex$INVOKER$i$0$0$synchronize.call(Mutex$INVOKER$i$0$0$synchronize.gen)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
container         | 	at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
container         | 	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
container         | 	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
container         | 	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.ast.IfNode.interpret(IfNode.java:118)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
container         | 	at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
container         | 	at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
container         | 	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:139)
container         | 	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:187)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)
container         | 	at org.jruby.ast.VCallNode.interpret(VCallNode.java:88)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
container         | 	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:204)
container         | 	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:211)
container         | 	at org.jruby.runtime.callsite.SuperCallSite.cacheAndCall(SuperCallSite.java:366)
container         | 	at org.jruby.runtime.callsite.SuperCallSite.callBlock(SuperCallSite.java:192)
container         | 	at org.jruby.runtime.callsite.SuperCallSite.call(SuperCallSite.java:197)
container         | 	at org.jruby.runtime.callsite.SuperCallSite.callVarargs(SuperCallSite.java:108)
container         | 	at org.jruby.ast.SuperNode.interpret(SuperNode.java:115)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
container         | 	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
container         | 	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
container         | 	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
container         | 	at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
container         | 	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
container         | 	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
container         | 	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
container         | 	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
container         | 	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
container         | 	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
container         | 	at usr.share.logstash.lib.bootstrap.environment.__file__(/usr/share/logstash/lib/bootstrap/environment.rb:71)
container         | 	at usr.share.logstash.lib.bootstrap.environment.load(/usr/share/logstash/lib/bootstrap/environment.rb)
container         | 	at org.jruby.Ruby.runScript(Ruby.java:857)
container         | 	at org.jruby.Ruby.runScript(Ruby.java:850)
container         | 	at org.jruby.Ruby.runNormally(Ruby.java:729)
container         | 	at org.jruby.Ruby.runFromMain(Ruby.java:578)
container         | 	at org.jruby.Main.doRunFromMain(Main.java:393)
container         | 	at org.jruby.Main.internalRun(Main.java:288)
container         | 	at org.jruby.Main.run(Main.java:217)
container         | 	at org.jruby.Main.main(Main.java:197)
container         | Caused by: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@3b92466e] unable to create manager for [my-logstash.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@7b677e33[pattern=my-logstash-%d{yyyy-MM-dd}.log, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=true)]), strategy=DefaultRolloverStrategy(min=1, max=7), advertiseURI=null, layout=[%d{ISO8601}][%-5p][%-25c{1.}] %marker%.10000m%n]]
container         | 	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:75)
container         | 	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:81)
container         | 	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:103)
container         | 	at org.apache.logging.log4j.core.appender.RollingFileAppender.createAppender(RollingFileAppender.java:191)
container         | 	... 98 more

Could any one help me?

Sorry for my English =)

**Comment by jarpy** [comment]
Hi,

Please send your:

- `logstash.yml`
- `Dockerfile` (if you are using one)
- Docker command line

I will try to replicate the issue.

Please bear in mind that logging to a file inside the container is usually not a great idea. When the container goes away, so does the log. By default, our image logs to STDOUT so that Docker can handle the logs using whatever logging driver you have configured.

**Comment by emarcelino** [comment]
Hi @jarpy 

Thank you for your attention.

I'm using Docker Compose. For ease I attached a zip file with all settings.

The `./config/pipeline/default.conf` file you can adjust or discard if you prefer.

You have every reason to log, but as I was giving Permission denied I decided to enter the container and give all necessary permissions to see if it helps, and even in my host I also gave all permissions, but I did not succeed.

Thanks again for your help.


[github.zip](https://github.com/elastic/logstash-docker/files/1361214/github.zip)

**Comment by jarpy** [comment]
Thanks for the zip file. Very helpful.

I see that you are bind-mounting the `data` and `log` directories from the host. Cool.

The Logstash process runs as UID 1000, so those directories need to be writeable by that user on the host system. Like so:

```
$ ls -ln
total 16
drwxr-xr-x 3 1020 1020 4096 Oct  6 02:25 config
drwxrwxr-x 4 1000 1000 4096 Oct  6 02:23 data
-rw-r--r-- 1 1020 1020  483 Oct  5 21:12 docker-compose.yml
drwxrwxr-x 2 1000 1000 4096 Oct  6 02:26 log
```

**Comment by emarcelino** [comment]
Strange, in my computer still giving the same error, even setting UID 1000.

Look, have you any idea what it might be?

I'm using macOS Sierra 10.12.6.

See below:

```
$ ls -ln
total 8
drwxr-xr-x  5 501   20    170  5 Out 21:14 config
drwxrwxr-x@ 6 1000  1000  204  5 Out 21:49 data
-rw-r--r--@ 1 501   20    483  5 Out 21:12 docker-compose.yml
drwxrwxr-x  2 1000  1000   68  5 Out 21:48 log
$ docker-compose up
Creating logstash ...
Creating logstash ... done
Attaching to logstash
logstash    | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash    | 2017-10-06 00:54:30,432 main ERROR Unable to create file logstash.log java.io.IOException: Permission denied
logstash    | 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
logstash    | 	at java.io.File.createNewFile(File.java:1012)
```

**Comment by jarpy** [comment]
Interesting. I think this is probably related to Docker on MacOS. It looks like ownership and permissions for bind-mounted files is quite complicated on Mac:

https://docs.docker.com/docker-for-mac/osxfs/

I think you might need to `chown` the files to the user that is running your Docker daemon. I don't have a Mac to test this right now, but I can try to find someone who does.
