### ISSUE TITLE
issues with latest logstash docker image

### ISSUE THREAD

**Issue by jamiebuxxx** [elastic/logstash-docker#71]
Hello, 
When trying to run `logstash-plugin install --development` on the latest docker image, we are getting the following errors

```
====> Build docker image for test
Sending build context to Docker daemon  124.9kB
Step 1/18 : FROM logstash
latest: Pulling from library/logstash
723254a2c089: Pull complete 
abe15a44e12f: Pull complete 
409a28e3cc3d: Pull complete 
a9511c68044a: Pull complete 
9d1b16e30bc8: Pull complete 
0fc5a09c9242: Pull complete 
d34976006493: Pull complete 
3b70003f0c10: Pull complete 
28c269c66aee: Pull complete 
d262de89628e: Pull complete 
2d6d89279b4d: Pull complete 
5ecd3cb56d42: Pull complete 
e8659ee27256: Pull complete 
7a837fab7c70: Pull complete 
a0b35e7de5d6: Pull complete 
11661c7d961e: Pull complete 
Digest: sha256:c42fbe030992aca1c02751467ae406f7155b77d1413320879d6550c1603ba274
Status: Downloaded newer image for logstash:latest
 ---> e4f449326d36
Step 2/18 : RUN logstash-plugin install --development
 ---> Running in 6bd9c5111185
Installing logstash-devutils, logstash-input-generator, logstash-codec-json, logstash-output-null, benchmark-ips, rspec, logstash-patterns-core, logstash-filter-grok, flores, stud, pry, rspec-wait, childprocess, ftw, logstash-output-elasticsearch, rspec-sequencing, gmetric, gelf, timecop, jdbc-derby, jdbc-mysql, jar-dependencies, logstash-codec-plain, logstash-codec-multiline, logstash-codec-json_lines, addressable, json, gzip, elasticsearch, logstash-filter-kv, logstash-filter-ruby, sinatra, webrick, poseidon, snappy, webmock, logstash-codec-line
Error Bundler::InstallError, retrying 1/10
An error occurred while installing webrick (1.4.2), and Bundler cannot continue.
Make sure that `gem install webrick -v '1.4.2'` succeeds before bundling.
WARNING: can not set Session#timeout=(0) no session context
Error Bundler::InstallError, retrying 2/10
An error occurred while installing webrick (1.4.2), and Bundler cannot continue.
Make sure that `gem install webrick -v '1.4.2'` succeeds before bundling.

Exception: java.lang.ThreadDeath thrown from the UncaughtExceptionHandler in thread "Thread-9"
Error Bundler::InstallError, retrying 3/10
An error occurred while installing webrick (1.4.2), and Bundler cannot continue.
Make sure that `gem install webrick -v '1.4.2'` succeeds before bundling.
WARNING: can not set Session#timeout=(0) no session context
Error Bundler::InstallError, retrying 4/10
An error occurred while installing webrick (1.4.2), and Bundler cannot continue.
Make sure that `gem install webrick -v '1.4.2'` succeeds before bundling.
Error Bundler::Fetcher::CertificateFailureError, retrying 5/10
Could not verify the SSL certificate for https://rubygems.org/quick/Marshal.4.8/rest-client-1.8.0-x86-mswin32.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Error Bundler::Fetcher::CertificateFailureError, retrying 6/10
Could not verify the SSL certificate for https://rubygems.org/quick/Marshal.4.8/rest-client-1.8.0-x86-mswin32.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Error Bundler::Fetcher::CertificateFailureError, retrying 7/10
Could not verify the SSL certificate for https://rubygems.org/quick/Marshal.4.8/rest-client-1.8.0-x86-mswin32.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Error Bundler::Fetcher::CertificateFailureError, retrying 8/10
Could not verify the SSL certificate for https://rubygems.org/quick/Marshal.4.8/rest-client-1.8.0-x86-mswin32.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Error Bundler::Fetcher::CertificateFailureError, retrying 9/10
Could not verify the SSL certificate for https://rubygems.org/quick/Marshal.4.8/rest-client-1.8.0-x86-mswin32.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Error Bundler::Fetcher::CertificateFailureError, retrying 10/10
Could not verify the SSL certificate for https://rubygems.org/quick/Marshal.4.8/rest-client-1.8.0-x86-mswin32.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Too many retries, aborting, caused by Bundler::Fetcher::CertificateFailureError
ERROR: Installation Aborted, message: Could not verify the SSL certificate for https://rubygems.org/quick/Marshal.4.8/rest-client-1.8.0-x86-mswin32.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
```
With regards to the `webrick` error, I found the following GitHub issue that apparently fixes the issue.

https://github.com/elastic/logstash/issues/8845

Not sure if this is a case of just needing to build an new image, but our Logstash test suite is currently broken due to this error.

**Comment by jamiebuxxx** [comment]
here's the error from inside the container with the following command: 
`JARS_DEBUG=true JARS_VERBOSE=true DEBUG=1 logstash-plugin install --development` 

```
Gem::InstallError: webrick requires Ruby version >= 2.3.0.
/usr/share/logstash/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:560:in `ensure_required_ruby_version_met'
/usr/share/logstash/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:782:in `pre_install_checks'
/usr/share/logstash/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:231:in `install'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/source/rubygems.rb:114:in `install'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/rubygems_integration.rb:131:in `preserve_paths'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/source/rubygems.rb:113:in `install'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:107:in `install_gem_from_spec'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:269:in `install_sequentially'
org/jruby/RubyArray.java:1613:in `each'
/usr/share/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201:in `each'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:268:in `install_sequentially'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:90:in `run'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:18:in `install'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli/install.rb:80:in `run'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli.rb:155:in `install'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli.rb:10:in `start'
/usr/share/logstash/lib/bootstrap/bundler.rb:168:in `execute_bundler'
/usr/share/logstash/lib/bootstrap/bundler.rb:129:in `invoke!'
/usr/share/logstash/lib/pluginmanager/install.rb:142:in `install_gems_list!'
/usr/share/logstash/lib/pluginmanager/install.rb:61:in `execute'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
/usr/share/logstash/lib/pluginmanager/main.rb:48:in `(root)'
Bundler::InstallError: An error occurred while installing webrick (1.4.2), and Bundler cannot continue.
Make sure that `gem install webrick -v '1.4.2'` succeeds before bundling.
  install_gem_from_spec at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:145
   install_sequentially at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:269
                   each at org/jruby/RubyArray.java:1613
                   each at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201
   install_sequentially at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:268
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:90
                install at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:18
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli/install.rb:80
                install at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli.rb:155
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/command.rb:27
         invoke_command at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:126
               dispatch at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor.rb:359
                  start at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/base.rb:440
                  start at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli.rb:10
        execute_bundler at /usr/share/logstash/lib/bootstrap/bundler.rb:168
                invoke! at /usr/share/logstash/lib/bootstrap/bundler.rb:129
     install_gems_list! at /usr/share/logstash/lib/pluginmanager/install.rb:142
                execute at /usr/share/logstash/lib/pluginmanager/install.rb:61
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                execute at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
                 (root) at /usr/share/logstash/lib/pluginmanager/main.rb:48
```

**Comment by jarpy** [comment]
Hi,

This repository is for the [images produced by Elastic](https://www.docker.elastic.co/#), but your Dockerfile is referencing the [old one from Docker Inc](https://hub.docker.com/_/logstash/).

Our image doesn't seem to suffer from this issue (yay!):

```
$ docker run --rm -it docker.elastic.co/logstash/logstash:6.1.1 logstash-plugin install --development
Installing logstash-devutils, logstash-input-generator, logstash-codec-json, logstash-output-null, benchmark-ips, rspec, jdbc-derby, jdbc-mysql, logstash-patterns-core, logstash-filter-grok, flores, stud, pry, rspec-wait, childprocess, rspec-sequencing, gmetric, gelf, ftw, timecop, jar-dependencies, logstash-codec-plain, logstash-codec-multiline, logstash-codec-json_lines, addressable, json, gzip, elasticsearch, rumbster, logstash-filter-kv, logstash-filter-ruby, sinatra, webrick, poseidon, snappy, webmock, logstash-codec-line, paquet, rake, json-schema, public_suffix, belzebuth
Installation successful
```

**Comment by jamiebuxxx** [comment]
Ah! That would do it. Didn't look at the Docker Hub page. I updated the image and it gets pass plugin install error. But not I'm unable to locate `rspec` to run my test. Is that not included in this image?
```
###  RUN PATTERN TESTS    #####################
/test/run-tests.sh: line 4: rspec: command not found

**Comment by jamiebuxxx** [comment]
Never mind, I see that is was removed. 
https://github.com/elastic/logstash/issues/6479. So, I think I'm going to have to build a custom image for our test.

**Comment by jarpy** [comment]
Hmm. Sorry.

Feel free to:

``` dockerfile
FROM docker.elastic.co/logstash/logstash:6.1.1
```

or

``` dockerfile
FROM docker.elastic.co/logstash/logstash-oss:6.1.1
```

If that helps any.

**Comment by jarpy** [comment]
I haven't tried it, I'm afraid. Perhaps @jamiebuxxx had some success and can be the hero here?

**Comment by jamiebuxxx** [comment]
@oivoodoo 
I built a custom image with `rspec` installed on it. Then in my Dockerfile I have the my specs and test added to the container. 

So in my Dockerfile
```
ADD $PATTERN_CONFIG /etc/logstash/patterns
ADD $LST/test /test
ADD $FILTER_CONFIG /test/spec/filter_config
ADD $FILTER_TESTS /test/spec/filter_data
ADD $PATTERN_TESTS /test/spec/pattern_data

ENTRYPOINT ["/test/run-tests.sh"]
```
Inside my `/test` directory I have the following script that run the specs(as you can see via the `ENTRYPOINT`).
```
#!/bin/bash

if [[ $1 == "all" || $1 == "patterns" ]]; then
  echo "###  RUN PATTERN TESTS    #####################"
  bin/rspec -f p /test/spec/patterns_spec.rb
fi

if [[ $1 == "all" || $1 == "filters" ]]; then
  echo "###  RUN FILTER Tests  ####################"
  if [[ $2 == "y" ]]; then
    bin/logstash -t -f /test/spec/filter_config
  fi
  bin/rspec -f p /test/spec/filter_spec.rb
fi
```
I'm sure there's a better way to do this, but its been working for a while now. Hope this helps.

**Comment by oivoodoo** [comment]
@jamiebuxxx 

finally did it, the only problem that I wanted to have 2.4.1 version in dockerfile. But hope it would work fine with the latest version as well:

My Dockerfile.

```Dockerfile
FROM docker.elastic.co/logstash/logstash:6.5.1

RUN logstash-plugin install --development

ADD rspec.dockerfile /opt/logstash/bin/rspec

WORKDIR /opt/logstash/
```

```rspec.dockerfile
#!/bin/sh

unset CDPATH
. "$(cd `dirname $0`/..; pwd)/bin/logstash.lib.sh"
setup

# use faster starting JRuby options see https://github.com/jruby/jruby/wiki/Improving-startup-time
export JRUBY_OPTS="$JRUBY_OPTS -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1"

ruby_exec "${LOGSTASH_HOME}/lib/bootstrap/rspec.rb" "$@"
```

found this rspec binary in the latest master version of logstash, probably it's not updated in base image.
